//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InetGlobalIndo.ERP.MTJ.DBFactory.ERPManSys.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=MTJ_ERP_Management_System;U" +
            "ser ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=MTJ_ERP_Management_System;U" +
            "ser ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString1 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=MTJ_ERP_Management_System;U" +
            "ser ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString2 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=MTJ_ERP_Management_System;P" +
            "ersist Security Info=True;User ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString3 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=MTJ_ERP_Management_System;P" +
            "ersist Security Info=True;User ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString4 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString4"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=MTJ_ERP_Management_System;P" +
            "ersist Security Info=True;User ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString5 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString5"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=MTJ_ERP_Management_System;P" +
            "ersist Security Info=True;User ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString6 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString6"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=MTJ_ERP_Management_System;P" +
            "ersist Security Info=True;User ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString7 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString7"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=MTJ_ERP_Management_System;P" +
            "ersist Security Info=True;User ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString8 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString8"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=MTJ_ERP_Management_System;P" +
            "ersist Security Info=True;User ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString9 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString9"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=MTJ_ERP_Management_System;P" +
            "ersist Security Info=True;User ID=sa;Password=password")]
        public string MTJ_ERP_Management_SystemConnectionString10 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString10"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\DEVELOPMENT;Initial Catalog=MTJ_ERP_Management_System;P" +
            "ersist Security Info=True;User ID=sa")]
        public string UNICOM_ERP_Management_SystemConnectionString {
            get {
                return ((string)(this["UNICOM_ERP_Management_SystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\DEVELOPMENT;Initial Catalog=MTJ_ERP_Management_System;P" +
            "ersist Security Info=True;User ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString11 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString11"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BIDHAVENSRV\\DEVELOPMENT;Initial Catalog=MTJ_ERP_Management_System;Per" +
            "sist Security Info=True;User ID=sa")]
        public string MTJ_ERP_Management_SystemConnectionString12 {
            get {
                return ((string)(this["MTJ_ERP_Management_SystemConnectionString12"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BIDHAVENSRV\\DEVELOPMENT;Initial Catalog=UNICOM_ERP_Management_System;" +
            "Persist Security Info=True;User ID=sa")]
        public string UNICOM_ERP_Management_SystemConnectionString1 {
            get {
                return ((string)(this["UNICOM_ERP_Management_SystemConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=BIDHAVENSRV\\DEVELOPMENT;Initial Catalog=SIP_ERP_Management_System;Per" +
            "sist Security Info=True;User ID=sa")]
        public string SIP_ERP_Management_SystemConnectionString {
            get {
                return ((string)(this["SIP_ERP_Management_SystemConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=MTJ_ERP_1\\DEVELOPMENT;Initial Catalog=SIP_ERP_Management_System;Persi" +
            "st Security Info=True;User ID=sa")]
        public string SIP_ERP_Management_SystemConnectionString1 {
            get {
                return ((string)(this["SIP_ERP_Management_SystemConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\DEVELOPMENT;Initial Catalog=UNICOM_ERP_Management_Syste" +
            "m;Persist Security Info=True;User ID=sa")]
        public string SIP_ERP_Management_SystemConnectionString2 {
            get {
                return ((string)(this["SIP_ERP_Management_SystemConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=SIP_ERP_Management_System;U" +
            "ser ID=sa;Password=password")]
        public string SIP_ERP_Management_SystemConnectionString3 {
            get {
                return ((string)(this["SIP_ERP_Management_SystemConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\DEVELOPMENT;Initial Catalog=UNICOM_ERP_Management_Syste" +
            "m;Persist Security Info=True;User ID=sa")]
        public string UNICOM_ERP_Management_SystemConnectionString2 {
            get {
                return ((string)(this["UNICOM_ERP_Management_SystemConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=SIP_ERP_Management_System;P" +
            "ersist Security Info=True;User ID=sa")]
        public string UNICOM_ERP_Management_SystemConnectionString3 {
            get {
                return ((string)(this["UNICOM_ERP_Management_SystemConnectionString3"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.2\\development;Initial Catalog=SIP_ERP_Management_System;U" +
            "ser ID=sa")]
        public string UNICOM_ERP_Management_SystemConnectionString4 {
            get {
                return ((string)(this["UNICOM_ERP_Management_SystemConnectionString4"]));
            }
        }
    }
}
