//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VTSWeb.Database.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "9.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.1\\development;Initial Catalog=CDC_VTS_Development;User ID" +
            "=vtsuser")]
        public string CDC_VTS_DevelopmentConnectionString {
            get {
                return ((string)(this["CDC_VTS_DevelopmentConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=192.168.100.1\\development;Initial Catalog=CDC_VTS_Development;User ID" +
            "=vtsuser;Password=vtsuser.1")]
        public string CDC_VTS_DevelopmentConnectionString1 {
            get {
                return ((string)(this["CDC_VTS_DevelopmentConnectionString1"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WEBACCESSSRV\\DEVELOPMENT;Initial Catalog=CDC_VTS_Development;User ID=" +
            "vtsuser;Password=vtsuser.1")]
        public string CDC_VTS_DevelopmentConnectionString2 {
            get {
                return ((string)(this["CDC_VTS_DevelopmentConnectionString2"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=WEBACCESSSRV\\DEVELOPMENT;Initial Catalog=CDC_VTS_Development;User ID=" +
            "vtsuser")]
        public string CDC_VTS_DevelopmentConnectionString3 {
            get {
                return ((string)(this["CDC_VTS_DevelopmentConnectionString3"]));
            }
        }
    }
}
