#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.4927
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMSLibrary
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="SMSPortal")]
	public partial class SMSDBDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMsBlockPhoneBook(MsBlockPhoneBook instance);
    partial void UpdateMsBlockPhoneBook(MsBlockPhoneBook instance);
    partial void DeleteMsBlockPhoneBook(MsBlockPhoneBook instance);
    partial void InsertMsCategory(MsCategory instance);
    partial void UpdateMsCategory(MsCategory instance);
    partial void DeleteMsCategory(MsCategory instance);
    partial void InsertTrAutoReply(TrAutoReply instance);
    partial void UpdateTrAutoReply(TrAutoReply instance);
    partial void DeleteTrAutoReply(TrAutoReply instance);
    partial void InsertTrSchedule(TrSchedule instance);
    partial void UpdateTrSchedule(TrSchedule instance);
    partial void DeleteTrSchedule(TrSchedule instance);
    partial void InsertMsBackEndSetting(MsBackEndSetting instance);
    partial void UpdateMsBackEndSetting(MsBackEndSetting instance);
    partial void DeleteMsBackEndSetting(MsBackEndSetting instance);
    partial void InsertSMSGatewaySend(SMSGatewaySend instance);
    partial void UpdateSMSGatewaySend(SMSGatewaySend instance);
    partial void DeleteSMSGatewaySend(SMSGatewaySend instance);
    partial void InsertMSPackage(MSPackage instance);
    partial void UpdateMSPackage(MSPackage instance);
    partial void DeleteMSPackage(MSPackage instance);
    partial void InsertMsCountryCode(MsCountryCode instance);
    partial void UpdateMsCountryCode(MsCountryCode instance);
    partial void DeleteMsCountryCode(MsCountryCode instance);
    partial void InsertSMSGatewayReceive(SMSGatewayReceive instance);
    partial void UpdateSMSGatewayReceive(SMSGatewayReceive instance);
    partial void DeleteSMSGatewayReceive(SMSGatewayReceive instance);
    partial void InsertMsUser(MsUser instance);
    partial void UpdateMsUser(MsUser instance);
    partial void DeleteMsUser(MsUser instance);
    partial void InsertMsOrganization(MsOrganization instance);
    partial void UpdateMsOrganization(MsOrganization instance);
    partial void DeleteMsOrganization(MsOrganization instance);
    partial void InsertTrBalance(TrBalance instance);
    partial void UpdateTrBalance(TrBalance instance);
    partial void DeleteTrBalance(TrBalance instance);
    partial void InsertMsPhoneBook(MsPhoneBook instance);
    partial void UpdateMsPhoneBook(MsPhoneBook instance);
    partial void DeleteMsPhoneBook(MsPhoneBook instance);
    #endregion
		
		public SMSDBDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDBDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDBDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public SMSDBDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<MsBlockPhoneBook> MsBlockPhoneBooks
		{
			get
			{
				return this.GetTable<MsBlockPhoneBook>();
			}
		}
		
		public System.Data.Linq.Table<MsCategory> MsCategories
		{
			get
			{
				return this.GetTable<MsCategory>();
			}
		}
		
		public System.Data.Linq.Table<TrAutoReply> TrAutoReplies
		{
			get
			{
				return this.GetTable<TrAutoReply>();
			}
		}
		
		public System.Data.Linq.Table<TrSchedule> TrSchedules
		{
			get
			{
				return this.GetTable<TrSchedule>();
			}
		}
		
		public System.Data.Linq.Table<MsBackEndSetting> MsBackEndSettings
		{
			get
			{
				return this.GetTable<MsBackEndSetting>();
			}
		}
		
		public System.Data.Linq.Table<SMSGatewaySend> SMSGatewaySends
		{
			get
			{
				return this.GetTable<SMSGatewaySend>();
			}
		}
		
		public System.Data.Linq.Table<MSPackage> MSPackages
		{
			get
			{
				return this.GetTable<MSPackage>();
			}
		}
		
		public System.Data.Linq.Table<MsCountryCode> MsCountryCodes
		{
			get
			{
				return this.GetTable<MsCountryCode>();
			}
		}
		
		public System.Data.Linq.Table<SMSGatewayReceive> SMSGatewayReceives
		{
			get
			{
				return this.GetTable<SMSGatewayReceive>();
			}
		}
		
		public System.Data.Linq.Table<MsUser> MsUsers
		{
			get
			{
				return this.GetTable<MsUser>();
			}
		}
		
		public System.Data.Linq.Table<MsOrganization> MsOrganizations
		{
			get
			{
				return this.GetTable<MsOrganization>();
			}
		}
		
		public System.Data.Linq.Table<TrBalance> TrBalances
		{
			get
			{
				return this.GetTable<TrBalance>();
			}
		}
		
		public System.Data.Linq.Table<MsPhoneBook> MsPhoneBooks
		{
			get
			{
				return this.GetTable<MsPhoneBook>();
			}
		}
	}
	
	[Table(Name="dbo.MsBlockPhoneBook")]
	public partial class MsBlockPhoneBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _BlockID;
		
		private long _OrganizationID;
		
		private string _UserID;
		
		private string _phoneNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnBlockIDChanging(long value);
    partial void OnBlockIDChanged();
    partial void OnOrganizationIDChanging(long value);
    partial void OnOrganizationIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnphoneNumberChanging(string value);
    partial void OnphoneNumberChanged();
    #endregion
		
		public MsBlockPhoneBook()
		{
			OnCreated();
		}
		
		[Column(Storage="_BlockID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long BlockID
		{
			get
			{
				return this._BlockID;
			}
			set
			{
				if ((this._BlockID != value))
				{
					this.OnBlockIDChanging(value);
					this.SendPropertyChanging();
					this._BlockID = value;
					this.SendPropertyChanged("BlockID");
					this.OnBlockIDChanged();
				}
			}
		}
		
		[Column(Storage="_OrganizationID", DbType="BigInt NOT NULL")]
		public long OrganizationID
		{
			get
			{
				return this._OrganizationID;
			}
			set
			{
				if ((this._OrganizationID != value))
				{
					this.OnOrganizationIDChanging(value);
					this.SendPropertyChanging();
					this._OrganizationID = value;
					this.SendPropertyChanged("OrganizationID");
					this.OnOrganizationIDChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_phoneNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string phoneNumber
		{
			get
			{
				return this._phoneNumber;
			}
			set
			{
				if ((this._phoneNumber != value))
				{
					this.OnphoneNumberChanging(value);
					this.SendPropertyChanging();
					this._phoneNumber = value;
					this.SendPropertyChanged("phoneNumber");
					this.OnphoneNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.MsCategory")]
	public partial class MsCategory : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _id;
		
		private string _Category;
		
		private string _SMSKeyword;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(byte value);
    partial void OnidChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnSMSKeywordChanging(string value);
    partial void OnSMSKeywordChanged();
    #endregion
		
		public MsCategory()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="TinyInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public byte id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_Category", DbType="VarChar(100)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[Column(Storage="_SMSKeyword", DbType="VarChar(50)")]
		public string SMSKeyword
		{
			get
			{
				return this._SMSKeyword;
			}
			set
			{
				if ((this._SMSKeyword != value))
				{
					this.OnSMSKeywordChanging(value);
					this.SendPropertyChanging();
					this._SMSKeyword = value;
					this.SendPropertyChanged("SMSKeyword");
					this.OnSMSKeywordChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.TrAutoReply")]
	public partial class TrAutoReply : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _OrganizationID;
		
		private string _KeyWord;
		
		private string _ReplyMessage;
		
		private string _PhoneNumber;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnOrganizationIDChanging(long value);
    partial void OnOrganizationIDChanged();
    partial void OnKeyWordChanging(string value);
    partial void OnKeyWordChanged();
    partial void OnReplyMessageChanging(string value);
    partial void OnReplyMessageChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    #endregion
		
		public TrAutoReply()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_OrganizationID", DbType="BigInt NOT NULL")]
		public long OrganizationID
		{
			get
			{
				return this._OrganizationID;
			}
			set
			{
				if ((this._OrganizationID != value))
				{
					this.OnOrganizationIDChanging(value);
					this.SendPropertyChanging();
					this._OrganizationID = value;
					this.SendPropertyChanged("OrganizationID");
					this.OnOrganizationIDChanged();
				}
			}
		}
		
		[Column(Storage="_KeyWord", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string KeyWord
		{
			get
			{
				return this._KeyWord;
			}
			set
			{
				if ((this._KeyWord != value))
				{
					this.OnKeyWordChanging(value);
					this.SendPropertyChanging();
					this._KeyWord = value;
					this.SendPropertyChanged("KeyWord");
					this.OnKeyWordChanged();
				}
			}
		}
		
		[Column(Storage="_ReplyMessage", DbType="VarChar(2000)")]
		public string ReplyMessage
		{
			get
			{
				return this._ReplyMessage;
			}
			set
			{
				if ((this._ReplyMessage != value))
				{
					this.OnReplyMessageChanging(value);
					this.SendPropertyChanging();
					this._ReplyMessage = value;
					this.SendPropertyChanged("ReplyMessage");
					this.OnReplyMessageChanged();
				}
			}
		}
		
		[Column(Storage="_PhoneNumber", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.TrSchedule")]
	public partial class TrSchedule : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _OrganizationID;
		
		private string _UserID;
		
		private System.Nullable<System.DateTime> _ScheduleDate;
		
		private string _Message;
		
		private string _DestinationPhoneNumber;
		
		private System.Nullable<bool> _fgQueuedSend;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnOrganizationIDChanging(long value);
    partial void OnOrganizationIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnScheduleDateChanging(System.Nullable<System.DateTime> value);
    partial void OnScheduleDateChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnDestinationPhoneNumberChanging(string value);
    partial void OnDestinationPhoneNumberChanged();
    partial void OnfgQueuedSendChanging(System.Nullable<bool> value);
    partial void OnfgQueuedSendChanged();
    #endregion
		
		public TrSchedule()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_OrganizationID", DbType="BigInt NOT NULL")]
		public long OrganizationID
		{
			get
			{
				return this._OrganizationID;
			}
			set
			{
				if ((this._OrganizationID != value))
				{
					this.OnOrganizationIDChanging(value);
					this.SendPropertyChanging();
					this._OrganizationID = value;
					this.SendPropertyChanged("OrganizationID");
					this.OnOrganizationIDChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_ScheduleDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ScheduleDate
		{
			get
			{
				return this._ScheduleDate;
			}
			set
			{
				if ((this._ScheduleDate != value))
				{
					this.OnScheduleDateChanging(value);
					this.SendPropertyChanging();
					this._ScheduleDate = value;
					this.SendPropertyChanged("ScheduleDate");
					this.OnScheduleDateChanged();
				}
			}
		}
		
		[Column(Storage="_Message", DbType="VarChar(2000)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[Column(Storage="_DestinationPhoneNumber", DbType="VarChar(50)")]
		public string DestinationPhoneNumber
		{
			get
			{
				return this._DestinationPhoneNumber;
			}
			set
			{
				if ((this._DestinationPhoneNumber != value))
				{
					this.OnDestinationPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._DestinationPhoneNumber = value;
					this.SendPropertyChanged("DestinationPhoneNumber");
					this.OnDestinationPhoneNumberChanged();
				}
			}
		}
		
		[Column(Storage="_fgQueuedSend", DbType="Bit")]
		public System.Nullable<bool> fgQueuedSend
		{
			get
			{
				return this._fgQueuedSend;
			}
			set
			{
				if ((this._fgQueuedSend != value))
				{
					this.OnfgQueuedSendChanging(value);
					this.SendPropertyChanging();
					this._fgQueuedSend = value;
					this.SendPropertyChanged("fgQueuedSend");
					this.OnfgQueuedSendChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.MsBackEndSetting")]
	public partial class MsBackEndSetting : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _Description;
		
		private string _Value;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    partial void OnValueChanging(string value);
    partial void OnValueChanged();
    #endregion
		
		public MsBackEndSetting()
		{
			OnCreated();
		}
		
		[Column(Storage="_Description", DbType="VarChar(100) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		[Column(Storage="_Value", DbType="VarChar(500)")]
		public string Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this.OnValueChanging(value);
					this.SendPropertyChanging();
					this._Value = value;
					this.SendPropertyChanged("Value");
					this.OnValueChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.SMSGatewaySend")]
	public partial class SMSGatewaySend : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _Category;
		
		private string _DestinationPhoneNo;
		
		private string _Message;
		
		private System.Nullable<byte> _flagSend;
		
		private string _userID;
		
		private System.Nullable<System.DateTime> _DateSent;
		
		private System.Nullable<long> _OrganizationID;
		
		private System.Nullable<bool> _fgMasking;
		
		private string _MaskingStatus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnDestinationPhoneNoChanging(string value);
    partial void OnDestinationPhoneNoChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnflagSendChanging(System.Nullable<byte> value);
    partial void OnflagSendChanged();
    partial void OnuserIDChanging(string value);
    partial void OnuserIDChanged();
    partial void OnDateSentChanging(System.Nullable<System.DateTime> value);
    partial void OnDateSentChanged();
    partial void OnOrganizationIDChanging(System.Nullable<long> value);
    partial void OnOrganizationIDChanged();
    partial void OnfgMaskingChanging(System.Nullable<bool> value);
    partial void OnfgMaskingChanged();
    partial void OnMaskingStatusChanging(string value);
    partial void OnMaskingStatusChanged();
    #endregion
		
		public SMSGatewaySend()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_Category", DbType="VarChar(50)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[Column(Storage="_DestinationPhoneNo", DbType="VarChar(50)")]
		public string DestinationPhoneNo
		{
			get
			{
				return this._DestinationPhoneNo;
			}
			set
			{
				if ((this._DestinationPhoneNo != value))
				{
					this.OnDestinationPhoneNoChanging(value);
					this.SendPropertyChanging();
					this._DestinationPhoneNo = value;
					this.SendPropertyChanged("DestinationPhoneNo");
					this.OnDestinationPhoneNoChanged();
				}
			}
		}
		
		[Column(Storage="_Message", DbType="VarChar(2000)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[Column(Storage="_flagSend", DbType="TinyInt")]
		public System.Nullable<byte> flagSend
		{
			get
			{
				return this._flagSend;
			}
			set
			{
				if ((this._flagSend != value))
				{
					this.OnflagSendChanging(value);
					this.SendPropertyChanging();
					this._flagSend = value;
					this.SendPropertyChanged("flagSend");
					this.OnflagSendChanged();
				}
			}
		}
		
		[Column(Storage="_userID", DbType="VarChar(50)")]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[Column(Storage="_DateSent", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateSent
		{
			get
			{
				return this._DateSent;
			}
			set
			{
				if ((this._DateSent != value))
				{
					this.OnDateSentChanging(value);
					this.SendPropertyChanging();
					this._DateSent = value;
					this.SendPropertyChanged("DateSent");
					this.OnDateSentChanged();
				}
			}
		}
		
		[Column(Storage="_OrganizationID", DbType="BigInt")]
		public System.Nullable<long> OrganizationID
		{
			get
			{
				return this._OrganizationID;
			}
			set
			{
				if ((this._OrganizationID != value))
				{
					this.OnOrganizationIDChanging(value);
					this.SendPropertyChanging();
					this._OrganizationID = value;
					this.SendPropertyChanged("OrganizationID");
					this.OnOrganizationIDChanged();
				}
			}
		}
		
		[Column(Storage="_fgMasking", DbType="Bit")]
		public System.Nullable<bool> fgMasking
		{
			get
			{
				return this._fgMasking;
			}
			set
			{
				if ((this._fgMasking != value))
				{
					this.OnfgMaskingChanging(value);
					this.SendPropertyChanging();
					this._fgMasking = value;
					this.SendPropertyChanged("fgMasking");
					this.OnfgMaskingChanged();
				}
			}
		}
		
		[Column(Storage="_MaskingStatus", DbType="VarChar(500)")]
		public string MaskingStatus
		{
			get
			{
				return this._MaskingStatus;
			}
			set
			{
				if ((this._MaskingStatus != value))
				{
					this.OnMaskingStatusChanging(value);
					this.SendPropertyChanging();
					this._MaskingStatus = value;
					this.SendPropertyChanged("MaskingStatus");
					this.OnMaskingStatusChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.MSPackage")]
	public partial class MSPackage : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _PackageName;
		
		private System.Nullable<int> _SMSPerDay;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPackageNameChanging(string value);
    partial void OnPackageNameChanged();
    partial void OnSMSPerDayChanging(System.Nullable<int> value);
    partial void OnSMSPerDayChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public MSPackage()
		{
			OnCreated();
		}
		
		[Column(Storage="_PackageName", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string PackageName
		{
			get
			{
				return this._PackageName;
			}
			set
			{
				if ((this._PackageName != value))
				{
					this.OnPackageNameChanging(value);
					this.SendPropertyChanging();
					this._PackageName = value;
					this.SendPropertyChanged("PackageName");
					this.OnPackageNameChanged();
				}
			}
		}
		
		[Column(Storage="_SMSPerDay", DbType="Int")]
		public System.Nullable<int> SMSPerDay
		{
			get
			{
				return this._SMSPerDay;
			}
			set
			{
				if ((this._SMSPerDay != value))
				{
					this.OnSMSPerDayChanging(value);
					this.SendPropertyChanging();
					this._SMSPerDay = value;
					this.SendPropertyChanged("SMSPerDay");
					this.OnSMSPerDayChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="VarChar(8000)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.MsCountryCode")]
	public partial class MsCountryCode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _CountryCode;
		
		private string _Remark;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnCountryCodeChanging(string value);
    partial void OnCountryCodeChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    #endregion
		
		public MsCountryCode()
		{
			OnCreated();
		}
		
		[Column(Storage="_CountryCode", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string CountryCode
		{
			get
			{
				return this._CountryCode;
			}
			set
			{
				if ((this._CountryCode != value))
				{
					this.OnCountryCodeChanging(value);
					this.SendPropertyChanging();
					this._CountryCode = value;
					this.SendPropertyChanged("CountryCode");
					this.OnCountryCodeChanged();
				}
			}
		}
		
		[Column(Storage="_Remark", DbType="VarChar(500)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.SMSGatewayReceive")]
	public partial class SMSGatewayReceive : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private string _Category;
		
		private string _SenderPhoneNo;
		
		private string _Message;
		
		private System.Nullable<byte> _flagRead;
		
		private string _userID;
		
		private System.Nullable<long> _ReplyId;
		
		private System.Nullable<System.DateTime> _DateReceived;
		
		private System.Nullable<long> _OrganizationID;
		
		private System.Nullable<bool> _fgSound;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnCategoryChanging(string value);
    partial void OnCategoryChanged();
    partial void OnSenderPhoneNoChanging(string value);
    partial void OnSenderPhoneNoChanged();
    partial void OnMessageChanging(string value);
    partial void OnMessageChanged();
    partial void OnflagReadChanging(System.Nullable<byte> value);
    partial void OnflagReadChanged();
    partial void OnuserIDChanging(string value);
    partial void OnuserIDChanged();
    partial void OnReplyIdChanging(System.Nullable<long> value);
    partial void OnReplyIdChanged();
    partial void OnDateReceivedChanging(System.Nullable<System.DateTime> value);
    partial void OnDateReceivedChanged();
    partial void OnOrganizationIDChanging(System.Nullable<long> value);
    partial void OnOrganizationIDChanged();
    partial void OnfgSoundChanging(System.Nullable<bool> value);
    partial void OnfgSoundChanged();
    #endregion
		
		public SMSGatewayReceive()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_Category", DbType="VarChar(50)")]
		public string Category
		{
			get
			{
				return this._Category;
			}
			set
			{
				if ((this._Category != value))
				{
					this.OnCategoryChanging(value);
					this.SendPropertyChanging();
					this._Category = value;
					this.SendPropertyChanged("Category");
					this.OnCategoryChanged();
				}
			}
		}
		
		[Column(Storage="_SenderPhoneNo", DbType="VarChar(50)")]
		public string SenderPhoneNo
		{
			get
			{
				return this._SenderPhoneNo;
			}
			set
			{
				if ((this._SenderPhoneNo != value))
				{
					this.OnSenderPhoneNoChanging(value);
					this.SendPropertyChanging();
					this._SenderPhoneNo = value;
					this.SendPropertyChanged("SenderPhoneNo");
					this.OnSenderPhoneNoChanged();
				}
			}
		}
		
		[Column(Storage="_Message", DbType="VarChar(2000)")]
		public string Message
		{
			get
			{
				return this._Message;
			}
			set
			{
				if ((this._Message != value))
				{
					this.OnMessageChanging(value);
					this.SendPropertyChanging();
					this._Message = value;
					this.SendPropertyChanged("Message");
					this.OnMessageChanged();
				}
			}
		}
		
		[Column(Storage="_flagRead", DbType="TinyInt")]
		public System.Nullable<byte> flagRead
		{
			get
			{
				return this._flagRead;
			}
			set
			{
				if ((this._flagRead != value))
				{
					this.OnflagReadChanging(value);
					this.SendPropertyChanging();
					this._flagRead = value;
					this.SendPropertyChanged("flagRead");
					this.OnflagReadChanged();
				}
			}
		}
		
		[Column(Storage="_userID", DbType="VarChar(50)")]
		public string userID
		{
			get
			{
				return this._userID;
			}
			set
			{
				if ((this._userID != value))
				{
					this.OnuserIDChanging(value);
					this.SendPropertyChanging();
					this._userID = value;
					this.SendPropertyChanged("userID");
					this.OnuserIDChanged();
				}
			}
		}
		
		[Column(Storage="_ReplyId", DbType="BigInt")]
		public System.Nullable<long> ReplyId
		{
			get
			{
				return this._ReplyId;
			}
			set
			{
				if ((this._ReplyId != value))
				{
					this.OnReplyIdChanging(value);
					this.SendPropertyChanging();
					this._ReplyId = value;
					this.SendPropertyChanged("ReplyId");
					this.OnReplyIdChanged();
				}
			}
		}
		
		[Column(Storage="_DateReceived", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateReceived
		{
			get
			{
				return this._DateReceived;
			}
			set
			{
				if ((this._DateReceived != value))
				{
					this.OnDateReceivedChanging(value);
					this.SendPropertyChanging();
					this._DateReceived = value;
					this.SendPropertyChanged("DateReceived");
					this.OnDateReceivedChanged();
				}
			}
		}
		
		[Column(Storage="_OrganizationID", DbType="BigInt")]
		public System.Nullable<long> OrganizationID
		{
			get
			{
				return this._OrganizationID;
			}
			set
			{
				if ((this._OrganizationID != value))
				{
					this.OnOrganizationIDChanging(value);
					this.SendPropertyChanging();
					this._OrganizationID = value;
					this.SendPropertyChanged("OrganizationID");
					this.OnOrganizationIDChanged();
				}
			}
		}
		
		[Column(Storage="_fgSound", DbType="Bit")]
		public System.Nullable<bool> fgSound
		{
			get
			{
				return this._fgSound;
			}
			set
			{
				if ((this._fgSound != value))
				{
					this.OnfgSoundChanging(value);
					this.SendPropertyChanging();
					this._fgSound = value;
					this.SendPropertyChanged("fgSound");
					this.OnfgSoundChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.MsUser")]
	public partial class MsUser : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OrganizationID;
		
		private string _UserID;
		
		private string _password;
		
		private bool _fgAdmin;
		
		private bool _fgWebAdmin;
		
		private System.Nullable<System.DateTime> _RegistrationDate;
		
		private System.Nullable<System.DateTime> _ExpiredDate;
		
		private string _PackageName;
		
		private System.Nullable<int> _SMSLimit;
		
		private System.Nullable<System.DateTime> _LastLimitReset;
		
		private string _Email;
		
		private System.Nullable<bool> _fgActive;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrganizationIDChanging(long value);
    partial void OnOrganizationIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OnfgAdminChanging(bool value);
    partial void OnfgAdminChanged();
    partial void OnfgWebAdminChanging(bool value);
    partial void OnfgWebAdminChanged();
    partial void OnRegistrationDateChanging(System.Nullable<System.DateTime> value);
    partial void OnRegistrationDateChanged();
    partial void OnExpiredDateChanging(System.Nullable<System.DateTime> value);
    partial void OnExpiredDateChanged();
    partial void OnPackageNameChanging(string value);
    partial void OnPackageNameChanged();
    partial void OnSMSLimitChanging(System.Nullable<int> value);
    partial void OnSMSLimitChanged();
    partial void OnLastLimitResetChanging(System.Nullable<System.DateTime> value);
    partial void OnLastLimitResetChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnfgActiveChanging(System.Nullable<bool> value);
    partial void OnfgActiveChanged();
    #endregion
		
		public MsUser()
		{
			OnCreated();
		}
		
		[Column(Storage="_OrganizationID", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long OrganizationID
		{
			get
			{
				return this._OrganizationID;
			}
			set
			{
				if ((this._OrganizationID != value))
				{
					this.OnOrganizationIDChanging(value);
					this.SendPropertyChanging();
					this._OrganizationID = value;
					this.SendPropertyChanged("OrganizationID");
					this.OnOrganizationIDChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_password", DbType="VarChar(200) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[Column(Storage="_fgAdmin", DbType="Bit NOT NULL")]
		public bool fgAdmin
		{
			get
			{
				return this._fgAdmin;
			}
			set
			{
				if ((this._fgAdmin != value))
				{
					this.OnfgAdminChanging(value);
					this.SendPropertyChanging();
					this._fgAdmin = value;
					this.SendPropertyChanged("fgAdmin");
					this.OnfgAdminChanged();
				}
			}
		}
		
		[Column(Storage="_fgWebAdmin", DbType="Bit NOT NULL")]
		public bool fgWebAdmin
		{
			get
			{
				return this._fgWebAdmin;
			}
			set
			{
				if ((this._fgWebAdmin != value))
				{
					this.OnfgWebAdminChanging(value);
					this.SendPropertyChanging();
					this._fgWebAdmin = value;
					this.SendPropertyChanged("fgWebAdmin");
					this.OnfgWebAdminChanged();
				}
			}
		}
		
		[Column(Storage="_RegistrationDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> RegistrationDate
		{
			get
			{
				return this._RegistrationDate;
			}
			set
			{
				if ((this._RegistrationDate != value))
				{
					this.OnRegistrationDateChanging(value);
					this.SendPropertyChanging();
					this._RegistrationDate = value;
					this.SendPropertyChanged("RegistrationDate");
					this.OnRegistrationDateChanged();
				}
			}
		}
		
		[Column(Storage="_ExpiredDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> ExpiredDate
		{
			get
			{
				return this._ExpiredDate;
			}
			set
			{
				if ((this._ExpiredDate != value))
				{
					this.OnExpiredDateChanging(value);
					this.SendPropertyChanging();
					this._ExpiredDate = value;
					this.SendPropertyChanged("ExpiredDate");
					this.OnExpiredDateChanged();
				}
			}
		}
		
		[Column(Storage="_PackageName", DbType="VarChar(50)")]
		public string PackageName
		{
			get
			{
				return this._PackageName;
			}
			set
			{
				if ((this._PackageName != value))
				{
					this.OnPackageNameChanging(value);
					this.SendPropertyChanging();
					this._PackageName = value;
					this.SendPropertyChanged("PackageName");
					this.OnPackageNameChanged();
				}
			}
		}
		
		[Column(Storage="_SMSLimit", DbType="Int")]
		public System.Nullable<int> SMSLimit
		{
			get
			{
				return this._SMSLimit;
			}
			set
			{
				if ((this._SMSLimit != value))
				{
					this.OnSMSLimitChanging(value);
					this.SendPropertyChanging();
					this._SMSLimit = value;
					this.SendPropertyChanged("SMSLimit");
					this.OnSMSLimitChanged();
				}
			}
		}
		
		[Column(Storage="_LastLimitReset", DbType="DateTime")]
		public System.Nullable<System.DateTime> LastLimitReset
		{
			get
			{
				return this._LastLimitReset;
			}
			set
			{
				if ((this._LastLimitReset != value))
				{
					this.OnLastLimitResetChanging(value);
					this.SendPropertyChanging();
					this._LastLimitReset = value;
					this.SendPropertyChanged("LastLimitReset");
					this.OnLastLimitResetChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="VarChar(200)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Column(Storage="_fgActive", DbType="Bit")]
		public System.Nullable<bool> fgActive
		{
			get
			{
				return this._fgActive;
			}
			set
			{
				if ((this._fgActive != value))
				{
					this.OnfgActiveChanging(value);
					this.SendPropertyChanging();
					this._fgActive = value;
					this.SendPropertyChanged("fgActive");
					this.OnfgActiveChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.MsOrganization")]
	public partial class MsOrganization : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _OrganizationID;
		
		private string _OrganizationName;
		
		private System.Nullable<int> _UserLimit;
		
		private string _BalanceCheckCode;
		
		private System.Nullable<bool> _BalanceCheckRequest;
		
		private string _LastBalance;
		
		private System.Nullable<bool> _GatewayStatus;
		
		private string _FooterAdditionalMessage;
		
		private string _GatewayStatusNoticeNumber;
		
		private System.Nullable<System.DateTime> _GatewayStatusNoticeLastSent;
		
		private string _GlobalReplyMessage;
		
		private string _Email;
		
		private System.Nullable<decimal> _MaskingBalanceAccount;
		
		private System.Nullable<int> _MaskingSD;
		
		private System.Nullable<bool> _FgHosted;
		
		private System.Nullable<int> _SignalStrength;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnOrganizationIDChanging(long value);
    partial void OnOrganizationIDChanged();
    partial void OnOrganizationNameChanging(string value);
    partial void OnOrganizationNameChanged();
    partial void OnUserLimitChanging(System.Nullable<int> value);
    partial void OnUserLimitChanged();
    partial void OnBalanceCheckCodeChanging(string value);
    partial void OnBalanceCheckCodeChanged();
    partial void OnBalanceCheckRequestChanging(System.Nullable<bool> value);
    partial void OnBalanceCheckRequestChanged();
    partial void OnLastBalanceChanging(string value);
    partial void OnLastBalanceChanged();
    partial void OnGatewayStatusChanging(System.Nullable<bool> value);
    partial void OnGatewayStatusChanged();
    partial void OnFooterAdditionalMessageChanging(string value);
    partial void OnFooterAdditionalMessageChanged();
    partial void OnGatewayStatusNoticeNumberChanging(string value);
    partial void OnGatewayStatusNoticeNumberChanged();
    partial void OnGatewayStatusNoticeLastSentChanging(System.Nullable<System.DateTime> value);
    partial void OnGatewayStatusNoticeLastSentChanged();
    partial void OnGlobalReplyMessageChanging(string value);
    partial void OnGlobalReplyMessageChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnMaskingBalanceAccountChanging(System.Nullable<decimal> value);
    partial void OnMaskingBalanceAccountChanged();
    partial void OnMaskingSDChanging(System.Nullable<int> value);
    partial void OnMaskingSDChanged();
    partial void OnFgHostedChanging(System.Nullable<bool> value);
    partial void OnFgHostedChanged();
    partial void OnSignalStrengthChanging(System.Nullable<int> value);
    partial void OnSignalStrengthChanged();
    #endregion
		
		public MsOrganization()
		{
			OnCreated();
		}
		
		[Column(Storage="_OrganizationID", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long OrganizationID
		{
			get
			{
				return this._OrganizationID;
			}
			set
			{
				if ((this._OrganizationID != value))
				{
					this.OnOrganizationIDChanging(value);
					this.SendPropertyChanging();
					this._OrganizationID = value;
					this.SendPropertyChanged("OrganizationID");
					this.OnOrganizationIDChanged();
				}
			}
		}
		
		[Column(Storage="_OrganizationName", DbType="VarChar(50)")]
		public string OrganizationName
		{
			get
			{
				return this._OrganizationName;
			}
			set
			{
				if ((this._OrganizationName != value))
				{
					this.OnOrganizationNameChanging(value);
					this.SendPropertyChanging();
					this._OrganizationName = value;
					this.SendPropertyChanged("OrganizationName");
					this.OnOrganizationNameChanged();
				}
			}
		}
		
		[Column(Storage="_UserLimit", DbType="Int")]
		public System.Nullable<int> UserLimit
		{
			get
			{
				return this._UserLimit;
			}
			set
			{
				if ((this._UserLimit != value))
				{
					this.OnUserLimitChanging(value);
					this.SendPropertyChanging();
					this._UserLimit = value;
					this.SendPropertyChanged("UserLimit");
					this.OnUserLimitChanged();
				}
			}
		}
		
		[Column(Storage="_BalanceCheckCode", DbType="VarChar(20)")]
		public string BalanceCheckCode
		{
			get
			{
				return this._BalanceCheckCode;
			}
			set
			{
				if ((this._BalanceCheckCode != value))
				{
					this.OnBalanceCheckCodeChanging(value);
					this.SendPropertyChanging();
					this._BalanceCheckCode = value;
					this.SendPropertyChanged("BalanceCheckCode");
					this.OnBalanceCheckCodeChanged();
				}
			}
		}
		
		[Column(Storage="_BalanceCheckRequest", DbType="Bit")]
		public System.Nullable<bool> BalanceCheckRequest
		{
			get
			{
				return this._BalanceCheckRequest;
			}
			set
			{
				if ((this._BalanceCheckRequest != value))
				{
					this.OnBalanceCheckRequestChanging(value);
					this.SendPropertyChanging();
					this._BalanceCheckRequest = value;
					this.SendPropertyChanged("BalanceCheckRequest");
					this.OnBalanceCheckRequestChanged();
				}
			}
		}
		
		[Column(Storage="_LastBalance", DbType="VarChar(500)")]
		public string LastBalance
		{
			get
			{
				return this._LastBalance;
			}
			set
			{
				if ((this._LastBalance != value))
				{
					this.OnLastBalanceChanging(value);
					this.SendPropertyChanging();
					this._LastBalance = value;
					this.SendPropertyChanged("LastBalance");
					this.OnLastBalanceChanged();
				}
			}
		}
		
		[Column(Storage="_GatewayStatus", DbType="Bit")]
		public System.Nullable<bool> GatewayStatus
		{
			get
			{
				return this._GatewayStatus;
			}
			set
			{
				if ((this._GatewayStatus != value))
				{
					this.OnGatewayStatusChanging(value);
					this.SendPropertyChanging();
					this._GatewayStatus = value;
					this.SendPropertyChanged("GatewayStatus");
					this.OnGatewayStatusChanged();
				}
			}
		}
		
		[Column(Storage="_FooterAdditionalMessage", DbType="VarChar(50)")]
		public string FooterAdditionalMessage
		{
			get
			{
				return this._FooterAdditionalMessage;
			}
			set
			{
				if ((this._FooterAdditionalMessage != value))
				{
					this.OnFooterAdditionalMessageChanging(value);
					this.SendPropertyChanging();
					this._FooterAdditionalMessage = value;
					this.SendPropertyChanged("FooterAdditionalMessage");
					this.OnFooterAdditionalMessageChanged();
				}
			}
		}
		
		[Column(Storage="_GatewayStatusNoticeNumber", DbType="VarChar(50)")]
		public string GatewayStatusNoticeNumber
		{
			get
			{
				return this._GatewayStatusNoticeNumber;
			}
			set
			{
				if ((this._GatewayStatusNoticeNumber != value))
				{
					this.OnGatewayStatusNoticeNumberChanging(value);
					this.SendPropertyChanging();
					this._GatewayStatusNoticeNumber = value;
					this.SendPropertyChanged("GatewayStatusNoticeNumber");
					this.OnGatewayStatusNoticeNumberChanged();
				}
			}
		}
		
		[Column(Storage="_GatewayStatusNoticeLastSent", DbType="DateTime")]
		public System.Nullable<System.DateTime> GatewayStatusNoticeLastSent
		{
			get
			{
				return this._GatewayStatusNoticeLastSent;
			}
			set
			{
				if ((this._GatewayStatusNoticeLastSent != value))
				{
					this.OnGatewayStatusNoticeLastSentChanging(value);
					this.SendPropertyChanging();
					this._GatewayStatusNoticeLastSent = value;
					this.SendPropertyChanged("GatewayStatusNoticeLastSent");
					this.OnGatewayStatusNoticeLastSentChanged();
				}
			}
		}
		
		[Column(Storage="_GlobalReplyMessage", DbType="VarChar(500)")]
		public string GlobalReplyMessage
		{
			get
			{
				return this._GlobalReplyMessage;
			}
			set
			{
				if ((this._GlobalReplyMessage != value))
				{
					this.OnGlobalReplyMessageChanging(value);
					this.SendPropertyChanging();
					this._GlobalReplyMessage = value;
					this.SendPropertyChanged("GlobalReplyMessage");
					this.OnGlobalReplyMessageChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Column(Storage="_MaskingBalanceAccount", DbType="Decimal(23,8)")]
		public System.Nullable<decimal> MaskingBalanceAccount
		{
			get
			{
				return this._MaskingBalanceAccount;
			}
			set
			{
				if ((this._MaskingBalanceAccount != value))
				{
					this.OnMaskingBalanceAccountChanging(value);
					this.SendPropertyChanging();
					this._MaskingBalanceAccount = value;
					this.SendPropertyChanged("MaskingBalanceAccount");
					this.OnMaskingBalanceAccountChanged();
				}
			}
		}
		
		[Column(Storage="_MaskingSD", DbType="Int")]
		public System.Nullable<int> MaskingSD
		{
			get
			{
				return this._MaskingSD;
			}
			set
			{
				if ((this._MaskingSD != value))
				{
					this.OnMaskingSDChanging(value);
					this.SendPropertyChanging();
					this._MaskingSD = value;
					this.SendPropertyChanged("MaskingSD");
					this.OnMaskingSDChanged();
				}
			}
		}
		
		[Column(Storage="_FgHosted", DbType="Bit")]
		public System.Nullable<bool> FgHosted
		{
			get
			{
				return this._FgHosted;
			}
			set
			{
				if ((this._FgHosted != value))
				{
					this.OnFgHostedChanging(value);
					this.SendPropertyChanging();
					this._FgHosted = value;
					this.SendPropertyChanged("FgHosted");
					this.OnFgHostedChanged();
				}
			}
		}
		
		[Column(Storage="_SignalStrength", DbType="Int")]
		public System.Nullable<int> SignalStrength
		{
			get
			{
				return this._SignalStrength;
			}
			set
			{
				if ((this._SignalStrength != value))
				{
					this.OnSignalStrengthChanging(value);
					this.SendPropertyChanging();
					this._SignalStrength = value;
					this.SendPropertyChanged("SignalStrength");
					this.OnSignalStrengthChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.TrBalance")]
	public partial class TrBalance : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private System.Nullable<long> _OrganizationID;
		
		private System.Nullable<bool> _fgIncrease;
		
		private System.Nullable<decimal> _Amount;
		
		private System.Nullable<System.DateTime> _TransDate;
		
		private string _Description;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnOrganizationIDChanging(System.Nullable<long> value);
    partial void OnOrganizationIDChanged();
    partial void OnfgIncreaseChanging(System.Nullable<bool> value);
    partial void OnfgIncreaseChanged();
    partial void OnAmountChanging(System.Nullable<decimal> value);
    partial void OnAmountChanged();
    partial void OnTransDateChanging(System.Nullable<System.DateTime> value);
    partial void OnTransDateChanged();
    partial void OnDescriptionChanging(string value);
    partial void OnDescriptionChanged();
    #endregion
		
		public TrBalance()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_OrganizationID", DbType="BigInt")]
		public System.Nullable<long> OrganizationID
		{
			get
			{
				return this._OrganizationID;
			}
			set
			{
				if ((this._OrganizationID != value))
				{
					this.OnOrganizationIDChanging(value);
					this.SendPropertyChanging();
					this._OrganizationID = value;
					this.SendPropertyChanged("OrganizationID");
					this.OnOrganizationIDChanged();
				}
			}
		}
		
		[Column(Storage="_fgIncrease", DbType="Bit")]
		public System.Nullable<bool> fgIncrease
		{
			get
			{
				return this._fgIncrease;
			}
			set
			{
				if ((this._fgIncrease != value))
				{
					this.OnfgIncreaseChanging(value);
					this.SendPropertyChanging();
					this._fgIncrease = value;
					this.SendPropertyChanged("fgIncrease");
					this.OnfgIncreaseChanged();
				}
			}
		}
		
		[Column(Storage="_Amount", DbType="Decimal(23,8)")]
		public System.Nullable<decimal> Amount
		{
			get
			{
				return this._Amount;
			}
			set
			{
				if ((this._Amount != value))
				{
					this.OnAmountChanging(value);
					this.SendPropertyChanging();
					this._Amount = value;
					this.SendPropertyChanged("Amount");
					this.OnAmountChanged();
				}
			}
		}
		
		[Column(Storage="_TransDate", DbType="DateTime")]
		public System.Nullable<System.DateTime> TransDate
		{
			get
			{
				return this._TransDate;
			}
			set
			{
				if ((this._TransDate != value))
				{
					this.OnTransDateChanging(value);
					this.SendPropertyChanging();
					this._TransDate = value;
					this.SendPropertyChanged("TransDate");
					this.OnTransDateChanged();
				}
			}
		}
		
		[Column(Storage="_Description", DbType="VarChar(500)")]
		public string Description
		{
			get
			{
				return this._Description;
			}
			set
			{
				if ((this._Description != value))
				{
					this.OnDescriptionChanging(value);
					this.SendPropertyChanging();
					this._Description = value;
					this.SendPropertyChanged("Description");
					this.OnDescriptionChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[Table(Name="dbo.MsPhoneBook")]
	public partial class MsPhoneBook : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _id;
		
		private long _OrganizationID;
		
		private string _UserID;
		
		private string _Name;
		
		private string _PhoneNumber;
		
		private string _Company;
		
		private System.Nullable<System.DateTime> _DateOfBirth;
		
		private string _Religion;
		
		private string _Email;
		
		private string _City;
		
		private string _PhoneBookGroup;
		
		private string _Remark;
		
		private System.Nullable<bool> _fgBirthDay;
		
		private string _BirthdayWishes;
		
		private System.Nullable<System.DateTime> _lastWishesSent;
		
		private string _JobTitle;
		
		private string _Address;
		
		private string _NameCardPicture;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(long value);
    partial void OnidChanged();
    partial void OnOrganizationIDChanging(long value);
    partial void OnOrganizationIDChanged();
    partial void OnUserIDChanging(string value);
    partial void OnUserIDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnPhoneNumberChanging(string value);
    partial void OnPhoneNumberChanged();
    partial void OnCompanyChanging(string value);
    partial void OnCompanyChanged();
    partial void OnDateOfBirthChanging(System.Nullable<System.DateTime> value);
    partial void OnDateOfBirthChanged();
    partial void OnReligionChanging(string value);
    partial void OnReligionChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnCityChanging(string value);
    partial void OnCityChanged();
    partial void OnPhoneBookGroupChanging(string value);
    partial void OnPhoneBookGroupChanged();
    partial void OnRemarkChanging(string value);
    partial void OnRemarkChanged();
    partial void OnfgBirthDayChanging(System.Nullable<bool> value);
    partial void OnfgBirthDayChanged();
    partial void OnBirthdayWishesChanging(string value);
    partial void OnBirthdayWishesChanged();
    partial void OnlastWishesSentChanging(System.Nullable<System.DateTime> value);
    partial void OnlastWishesSentChanged();
    partial void OnJobTitleChanging(string value);
    partial void OnJobTitleChanged();
    partial void OnAddressChanging(string value);
    partial void OnAddressChanged();
    partial void OnNameCardPictureChanging(string value);
    partial void OnNameCardPictureChanged();
    #endregion
		
		public MsPhoneBook()
		{
			OnCreated();
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="BigInt NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public long id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_OrganizationID", DbType="BigInt NOT NULL")]
		public long OrganizationID
		{
			get
			{
				return this._OrganizationID;
			}
			set
			{
				if ((this._OrganizationID != value))
				{
					this.OnOrganizationIDChanging(value);
					this.SendPropertyChanging();
					this._OrganizationID = value;
					this.SendPropertyChanged("OrganizationID");
					this.OnOrganizationIDChanged();
				}
			}
		}
		
		[Column(Storage="_UserID", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string UserID
		{
			get
			{
				return this._UserID;
			}
			set
			{
				if ((this._UserID != value))
				{
					this.OnUserIDChanging(value);
					this.SendPropertyChanging();
					this._UserID = value;
					this.SendPropertyChanged("UserID");
					this.OnUserIDChanged();
				}
			}
		}
		
		[Column(Storage="_Name", DbType="VarChar(50)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[Column(Storage="_PhoneNumber", DbType="VarChar(50)")]
		public string PhoneNumber
		{
			get
			{
				return this._PhoneNumber;
			}
			set
			{
				if ((this._PhoneNumber != value))
				{
					this.OnPhoneNumberChanging(value);
					this.SendPropertyChanging();
					this._PhoneNumber = value;
					this.SendPropertyChanged("PhoneNumber");
					this.OnPhoneNumberChanged();
				}
			}
		}
		
		[Column(Storage="_Company", DbType="VarChar(50)")]
		public string Company
		{
			get
			{
				return this._Company;
			}
			set
			{
				if ((this._Company != value))
				{
					this.OnCompanyChanging(value);
					this.SendPropertyChanging();
					this._Company = value;
					this.SendPropertyChanged("Company");
					this.OnCompanyChanged();
				}
			}
		}
		
		[Column(Storage="_DateOfBirth", DbType="DateTime")]
		public System.Nullable<System.DateTime> DateOfBirth
		{
			get
			{
				return this._DateOfBirth;
			}
			set
			{
				if ((this._DateOfBirth != value))
				{
					this.OnDateOfBirthChanging(value);
					this.SendPropertyChanging();
					this._DateOfBirth = value;
					this.SendPropertyChanged("DateOfBirth");
					this.OnDateOfBirthChanged();
				}
			}
		}
		
		[Column(Storage="_Religion", DbType="VarChar(50)")]
		public string Religion
		{
			get
			{
				return this._Religion;
			}
			set
			{
				if ((this._Religion != value))
				{
					this.OnReligionChanging(value);
					this.SendPropertyChanging();
					this._Religion = value;
					this.SendPropertyChanged("Religion");
					this.OnReligionChanged();
				}
			}
		}
		
		[Column(Storage="_Email", DbType="VarChar(50)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[Column(Storage="_City", DbType="VarChar(50)")]
		public string City
		{
			get
			{
				return this._City;
			}
			set
			{
				if ((this._City != value))
				{
					this.OnCityChanging(value);
					this.SendPropertyChanging();
					this._City = value;
					this.SendPropertyChanged("City");
					this.OnCityChanged();
				}
			}
		}
		
		[Column(Storage="_PhoneBookGroup", DbType="VarChar(50)")]
		public string PhoneBookGroup
		{
			get
			{
				return this._PhoneBookGroup;
			}
			set
			{
				if ((this._PhoneBookGroup != value))
				{
					this.OnPhoneBookGroupChanging(value);
					this.SendPropertyChanging();
					this._PhoneBookGroup = value;
					this.SendPropertyChanged("PhoneBookGroup");
					this.OnPhoneBookGroupChanged();
				}
			}
		}
		
		[Column(Storage="_Remark", DbType="VarChar(500)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this.OnRemarkChanging(value);
					this.SendPropertyChanging();
					this._Remark = value;
					this.SendPropertyChanged("Remark");
					this.OnRemarkChanged();
				}
			}
		}
		
		[Column(Storage="_fgBirthDay", DbType="Bit")]
		public System.Nullable<bool> fgBirthDay
		{
			get
			{
				return this._fgBirthDay;
			}
			set
			{
				if ((this._fgBirthDay != value))
				{
					this.OnfgBirthDayChanging(value);
					this.SendPropertyChanging();
					this._fgBirthDay = value;
					this.SendPropertyChanged("fgBirthDay");
					this.OnfgBirthDayChanged();
				}
			}
		}
		
		[Column(Storage="_BirthdayWishes", DbType="VarChar(500)")]
		public string BirthdayWishes
		{
			get
			{
				return this._BirthdayWishes;
			}
			set
			{
				if ((this._BirthdayWishes != value))
				{
					this.OnBirthdayWishesChanging(value);
					this.SendPropertyChanging();
					this._BirthdayWishes = value;
					this.SendPropertyChanged("BirthdayWishes");
					this.OnBirthdayWishesChanged();
				}
			}
		}
		
		[Column(Storage="_lastWishesSent", DbType="DateTime")]
		public System.Nullable<System.DateTime> lastWishesSent
		{
			get
			{
				return this._lastWishesSent;
			}
			set
			{
				if ((this._lastWishesSent != value))
				{
					this.OnlastWishesSentChanging(value);
					this.SendPropertyChanging();
					this._lastWishesSent = value;
					this.SendPropertyChanged("lastWishesSent");
					this.OnlastWishesSentChanged();
				}
			}
		}
		
		[Column(Storage="_JobTitle", DbType="VarChar(50)")]
		public string JobTitle
		{
			get
			{
				return this._JobTitle;
			}
			set
			{
				if ((this._JobTitle != value))
				{
					this.OnJobTitleChanging(value);
					this.SendPropertyChanging();
					this._JobTitle = value;
					this.SendPropertyChanged("JobTitle");
					this.OnJobTitleChanged();
				}
			}
		}
		
		[Column(Storage="_Address", DbType="VarChar(500)")]
		public string Address
		{
			get
			{
				return this._Address;
			}
			set
			{
				if ((this._Address != value))
				{
					this.OnAddressChanging(value);
					this.SendPropertyChanging();
					this._Address = value;
					this.SendPropertyChanged("Address");
					this.OnAddressChanged();
				}
			}
		}
		
		[Column(Storage="_NameCardPicture", DbType="VarChar(500)")]
		public string NameCardPicture
		{
			get
			{
				return this._NameCardPicture;
			}
			set
			{
				if ((this._NameCardPicture != value))
				{
					this.OnNameCardPictureChanging(value);
					this.SendPropertyChanging();
					this._NameCardPicture = value;
					this.SendPropertyChanged("NameCardPicture");
					this.OnNameCardPictureChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
